language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "alBCg3daD4XoQOG8YM+36V1uDVo1PVOOPFN5gUm3c4Q1MIebGIqg/RCiuOnV39dqx4IM+hlBOR/KOzP6IMWfW4Ug9Zfixhtg6B0I4cA9mf41suYAUB23DhovAOU1R8Q6ojw2m+HinYhnTfy9hRzGgGnyoktQFVxVb8B6pXjaizzp78giIqtd+Xp6srWcXOKm6nKwOwacy2TMtakE4kPN68K/cM5NpdYBPewOB6rBmipgYRcjEgpnJSN6kJJtCNvwBiDPddjwk84FAE8KUbrTgfFjcnG8LXUSKeZXPLDhUfIXiHQtWAyKQSjeIt0hAWo0kcNquza644M4oPQOEkzyFItiAh+CjFmk16xnUFvNeVvrLaGnPrWmHE6teO6V1E2FgPK0VN2tLf5B0Pmb9whk82g1AL+fqkTKfIv6nTZQkdq+wCrjpf/DgmAyiE/rgJC5hGsPoBNp2EHMFu8IVE7oinUndOqMXxnCzw1u7xNBLUiYXzpYs9Z0mfa+ywQgp0ydO9eCIpjHa5infM9JLwO+ZDeurjhfGDI4xhq83ptOy8qNfdM2y1A5cU++/nPixp7GWkST8J7UYuA8NoE7luEBiLPAYrsuR4cek/OiWYWqmnhy2VW+G7Mj8VR7xA/apYmilpCGDqy0GrDZZzZvoSvye4zX8W3cTE1S6iGnhQhM/xY="

addons:
  coverity_scan:
    project:
      name: "dreibh/tsctp"
      description: "tsctp"
    notification_email: dreibh@simula.no
    build_command_prepend: "cmake ."
    build_command: "make -j2"
    branch_pattern: coverity_scan

script:
  - cmake .
  - make -j2
