language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "jPpqZn1qlQGpOa7T0qZrw/TGH/oT/E2VfuncmuJh7XFp15XfrhEINlyuERUj5fgHy5WNZDPtdPCKsFApcYiIC0TJ2Va60Dzj0bwWj94ahr+DaNmVbohT5xRIhH4ANSz1p0NbUQiAkoZW3MCCwqracrsnfAyZTZcZONLAUgjBh+BXlwU1KHSpoIxznjW42fZBXZ0hEAtu6A8tcHCwIOQQbyDZdJlOZyDJdeKY2gHKBOKTudSfQtJlQK60MqeLscVQAW6vm7PxUpWyhkrpZcVITSMEVTplEWHHhEzVlhW9OYZGoLMGRpyT/n0ng1mMt9qA09OQfoZBY9ep1R3nl+ml1WyCYtHZs77bcHx+mFRv1iuIziVKU0eSAXR0p4m3Cwb8s9JhOa6qCzYwI/n/62Dqv3/JNOD17Vcy7VUzRzOsVhEEQBs2EKUnKo1SYWGGqtQyiskRTauph6Yle3tO5unGa7ZPnLSdXcLZaa2oKsLqn+eleBRDcrfVRL8843O27Z6JtitZeuG/IgJwikAC/qaeQZn5CI6Nm+2QScHnTPmhljrM79NV6sXM/uKrjf4QYF91ezAmTj7MXDRrytOC8gau9MtolddHbn4AwW3BrU++y03thj1RTOhQsHw9oicG+Vnw5gb2+jw7bCwaNon/aje6jUu5pDDJz5MLhI/atC4htMY="

addons:
  coverity_scan:
    project:
      name: "tsctp"
      description: "SCTP Test Tool"
    notification_email: dreibh@simula.no
    build_command_prepend: "cmake ."
    build_command: "make -j2"
    branch_pattern: coverity_scan

script:
  - cmake .
  - make -j2
