language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      group: travis_latest
      env: DOCKER="ubuntu:xenial"
    #- os: linux
    #  dist: trusty
    #  compiler: clang
    #  group: travis_latest
    #- os: osx
    #  osx_image: xcode9.4
    #  compiler: clang
    #  group: travis_latest


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo docker run -d --name ubuntu-test -v $(pwd):/travis -w /travis $DOCKER tail -f /dev/null
       sudo docker ps
    elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
       brew update
       brew install bzip2 qt glib
    fi


install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo docker exec -t ubuntu-test bash -c apt-get install -y autoconf automake libsctp-dev
    fi


script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo docker exec -t ubuntu-test bash -c   ./bootstrap
       sudo docker exec -t ubuntu-test bash -c   ./configure
       sudo docker exec -t ubuntu-test bash -c   make VERBOSE=1
    fi
