language: c

matrix:
  include:

    # ====== Ubuntu 18.04 (Bionic Beaver) ===================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" COMPILER_C=clang COMPILER_CXX=clang++

    # ====== Ubuntu 16.04 (Xenial Xerus) ====================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:xenial" COMPILER_C=gcc COMPILER_CXX=g++

    # ====== MacOS X ========================================================
    #- os: osx
    #  osx_image: xcode9.4
    #  compiler: clang
    #  group: travis_latest


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo docker run -d --name ubuntu-test -v $(pwd):/travis -w /travis $DOCKER tail -f /dev/null
       sudo docker ps
    elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
       brew update
       brew install ...
    fi


install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo docker exec -t ubuntu-test bash -c "apt-get update"
       sudo docker exec -t ubuntu-test bash -c "apt-get install -y autoconf automake gcc g++ clang make libsctp-dev"
    fi


script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo docker exec -t ubuntu-test bash -c "./bootstrap"
       sudo docker exec -t ubuntu-test bash -c "echo OPTIONS: CC=$COMPILER_C CXX=$COMPILER_CXX"
       sudo docker exec -t ubuntu-test bash -c "env CC=$CC CXX=$CXX ./configure"
       sudo docker exec -t ubuntu-test bash -c "make VERBOSE=1"
    fi
