language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      group: travis_latest
    - os: linux
      dist: trusty
      compiler: clang
      group: travis_latest
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      group: travis_latest


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
       sudo apt-get update
       sudo apt-get install -y autoconf automake libsctp-dev
    elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
       brew update
       brew install autoconf automake
    fi

script:
  - |
    ./bootstrap
    ./configure
    make VERBOSE=1
