language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "alBCg3daD4XoQOG8YM+36V1uDVo1PVOOPFN5gUm3c4Q1MIebGIqg/RCiuOnV39dqx4IM+hlBOR/KOzP6IMWfW4Ug9Zfixhtg6B0I4cA9mf41suYAUB23DhovAOU1R8Q6ojw2m+HinYhnTfy9hRzGgGnyoktQFVxVb8B6pXjaizzp78giIqtd+Xp6srWcXOKm6nKwOwacy2TMtakE4kPN68K/cM5NpdYBPewOB6rBmipgYRcjEgpnJSN6kJJtCNvwBiDPddjwk84FAE8KUbrTgfFjcnG8LXUSKeZXPLDhUfIXiHQtWAyKQSjeIt0hAWo0kcNquza644M4oPQOEkzyFItiAh+CjFmk16xnUFvNeVvrLaGnPrWmHE6teO6V1E2FgPK0VN2tLf5B0Pmb9whk82g1AL+fqkTKfIv6nTZQkdq+wCrjpf/DgmAyiE/rgJC5hGsPoBNp2EHMFu8IVE7oinUndOqMXxnCzw1u7xNBLUiYXzpYs9Z0mfa+ywQgp0ydO9eCIpjHa5infM9JLwO+ZDeurjhfGDI4xhq83ptOy8qNfdM2y1A5cU++/nPixp7GWkST8J7UYuA8NoE7luEBiLPAYrsuR4cek/OiWYWqmnhy2VW+G7Mj8VR7xA/apYmilpCGDqy0GrDZZzZvoSvye4zX8W3cTE1S6iGnhQhM/xY="

matrix:
  include:

    # ###### Ubuntu Linux ###################################################

    # ====== Ubuntu 18.10 (Cosmic Cuttlefish) ===============================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:cosmic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:cosmic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:cosmic" VARIANT="ubuntu" TOOL="pbuilder"

    # ====== Ubuntu 18.04 (Bionic Beaver) ===================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

    # ====== Ubuntu 16.04 (Xenial Xerus) ====================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="pbuilder"

    # ====== Ubuntu 14.04 (Trusty Tahr) ====================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="pbuilder"


     # ###### Debian Linux ##################################################

     # ====== Debian Testing ================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:testing" VARIANT="debian" TOOL="pbuilder"

    # ====== Debian Sid =====================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:sid" VARIANT="debian" TOOL="pbuilder"

    # ====== Debian Buster ==================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:buster" VARIANT="debian" TOOL="pbuilder"

    # ====== Debian Stretch =================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="debian:stretch" VARIANT="debian" TOOL="pbuilder"


    ## ###### Fedora Linux ###################################################

    # ====== Fedora 30 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:30" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:30" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:30" VARIANT="fedora" TOOL="mock"

    # ====== Fedora 29 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:29" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:29" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:29" VARIANT="fedora" TOOL="mock"

    # ====== Fedora 28 ======================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:28" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:28" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:28" VARIANT="fedora" TOOL="mock"

    # ====== Fedora Rawhide =================================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="mock"


    # ###### Other ##########################################################

    # ====== MacOS X ========================================================
    #- os: osx
    #  osx_image: xcode9.4
    #  compiler: clang
    #  group: travis_latest


before_install:
  - |
    travis_wait 60 ci/before-install


install:
  - |
    travis_wait 60 ci/install


script:
  - |
    travis_wait 60 ci/build
    travis_wait 60 ci/test


addons:
  coverity_scan:
    project:
      name: "dreibh/tsctp"
      description: "tsctp"
    notification_email: dreibh@simula.no
    build_command_prepend: "cmake ."
    build_command: "make"
    branch_pattern: master   # coverity_scan
