language: c

matrix:
  include:

    # ###### Ubuntu Linux ###################################################

    ## ====== Ubuntu (latest version) ========================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="ubuntu:latest" VARIANT="ubuntu" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="ubuntu:latest" VARIANT="ubuntu" COMPILER_C="clang" COMPILER_CXX="clang++"

    # ====== Ubuntu 18.04 (Bionic Beaver) ===================================
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
    - os: linux
      dist: xenial
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

    ## ====== Ubuntu 16.04 (Xenial Xerus) ====================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" COMPILER_C="clang" COMPILER_CXX="clang++"

    ## ====== Ubuntu 14.04 (Trusty Tahr) ====================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" COMPILER_C="clang" COMPILER_CXX="clang++"


     ## ###### Debian Linux ##################################################

     ## ====== Debian Testing ================================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="debian:testing" VARIANT="ubuntu" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="debian:testing" VARIANT="ubuntu" COMPILER_C="clang" COMPILER_CXX="clang++"

    ## ====== Debian Stretch =================================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="debian:stretch" VARIANT="ubuntu" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="debian:stretch" VARIANT="ubuntu" COMPILER_C="clang" COMPILER_CXX="clang++"

    ## ====== Debian Sid =====================================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="debian:sid" VARIANT="ubuntu" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="debian:sid" VARIANT="ubuntu" COMPILER_C="clang" COMPILER_CXX="clang++"


    ## ###### Fedora Linux ###################################################

    ## ====== Fedora 29 ======================================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="fedora:29" VARIANT="fedora" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="fedora:29" VARIANT="fedora" COMPILER_C="clang" COMPILER_CXX="clang++"

    ## ====== Fedora Rawhide =================================================
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="fedora:rawhide" VARIANT="fedora" COMPILER_C="gcc" COMPILER_CXX="g++"
    #- os: linux
      #dist: xenial
      #group: travis_latest
      #env: DOCKER="fedora:rawhide" VARIANT="fedora" COMPILER_C="clang" COMPILER_CXX="clang++"


    # ###### Other ##########################################################

    # ====== MacOS X ========================================================
    #- os: osx
    #  osx_image: xcode9.4
    #  compiler: clang
    #  group: travis_latest


before_install:
  - |
    ci/before-install


install:
  - |
    ci/install


script:
  - |
    ci/build
