language: c
compiler:
  - gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "N8eNHtUu7wY4R1URWmUQ0XjXCPTtWtKBwjmH/lSIJtDeKwppSZRWxCoOlLaf51N3Kj0olcX53lRaBlDC08ikbmrjRrxGnYQKGiMfn0UCNK/W0bEDDHVuFIEwoo6Uv4bLcE/EUM5AuI+ejzUFH5pazMrFzb4nZ+pJ7C3vNeCgVa9c9yJpJYJ2+blpUzxvKMnKmk14ySI+iJ6M+ZIH8FJWUcVyoLYjzh8jJ5WaX6pNi186Sv+LAK5crTMJfJI4pIrAkKb67zvKN74hQdjJDzcGDlMwyPtGcfOwB0nJPdIxkBDwNd51+sIL1g/P7H4McmOSd2V9lRZUT1gekiZT01S9/Vyk99IKvL2kHKvpZjInt8WMR/32hJVKqRQNLlmW1CddbbDMgIH8yJxhbX9IDJSXKT7FqhMKWRdnbNkra6NPSLs0Igv1q1ppfwZlFQ/feDbSvfPf90hwAKPWRfzW76ab/8XKeqxB31cOP4vU1lnA87SpvFpelwguyF0Tlnr52xVACzV/Ari/NXfaGnTVAN41Ir+dQECfImuCtmO6iRvEndU8LxE28mz4kM26O5xOP8UES0lpc/vxrFh8sGgcIy+P6a2bUEZ8J1J2bKGD1oneNfDjJytxSe7+mlFAhba0V4Q4jNfgAGVkURqlV10Dh3AUB4tAziyzNPoyUl/7YgpIslY="

addons:
  coverity_scan:
    project:
      name: "dreibh/tsctp"
      description: "SCTP Test Tool"
    notification_email: dreibh@simula.no
    build_command_prepend: "cmake ."
    build_command: "make -j2"
    branch_pattern: coverity_scan

script:
  - cmake .
  - make -j2
