#!/bin/sh -eu
#
# Dia Scripts
# Copyright (C) 2007-2025 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

for figure in SCTPProject ; do
   dia -n -t cairo-pdf -e tmp1.pdf $figure.dia

   # ====== Make PDF with transparent background ============================
   epstopdf --outfile=tmp1.eps tmp1.pdf
   pdfcrop --hires tmp1.eps tmp2.pdf

#    pdfcrop --hires tmp1.pdf tmp2.pdf

   qpdf -qdf tmp2.pdf tmp1.qdf
   sed -e '0,/^.* re$/s/^\(.* re\)$/%% \1/' \
       -e '0,/^1 1 1 rg.*$/s/^\(1 1 1 rg.*\)$/%% \1/' \
      <tmp1.qdf >tmp2.qdf

   ls -l tmp1.qdf tmp2.qdf

   fix-qdf tmp2.qdf >$figure.pdf

   colordiff tmp1.qdf tmp2.qdf || true

   # ====== Make SVG, with transparent background ===========================
   pdf2svg $figure.pdf tmp1.svg
   sed \
      -e 's#\(<rect [^>]*fill-opacity="\)\([0-9\.]*\)\("/>\)#\10\3#g' \
      <tmp1.svg >$figure.svg

   # ====== Make PNG and WebP, with transparent background ==================
   gm convert -density 300x300 -transparent white $figure.pdf $figure.png
   gm convert -density 300x300 -transparent white $figure.pdf $figure.webp

   rm -f tmp1.pdf tmp1.eps tmp1.svg
done
