#!/bin/bash

# ###### Linux ##############################################################
if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
   if [ "$TOOL" = "compile" ] ; then
      sudo docker exec -t ubuntu-test bash -c "cmake ."
      sudo docker exec -t ubuntu-test bash -c "echo OPTIONS: CC=$COMPILER_C CXX=$COMPILER_CXX"
      sudo docker exec -t ubuntu-test bash -c "env CC=$COMPILER_C CXX=$COMPILER_CXX ./configure"
      sudo docker exec -t ubuntu-test bash -c "make VERBOSE=1"

   elif [ "$TOOL" = "pbuilder" ] ; then
      sudo docker exec -t ubuntu-test bash -c "env LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8 ./build-deb"

   elif [ "$TOOL" = "mock" ] ; then
      release=`cat /etc/fedora-release | sed -e "s/^\(.*\) release \([0-9]*\) (\(.*\))$/\2/g"`
      buildFor="fedora-$release-x86_64"
      sudo docker exec -t ubuntu-test bash -c "./make-rpm $buildFor"

   else
      echo >&2 "ERROR: Invalid setting of TOOL=$TOOL"
      exit 1
   fi

# ###### Other ##############################################################
elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
   cmake .
   make VERBOSE=1

# ###### Error ##############################################################
else
   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
   exit 1
fi
