#!/usr/bin/env bash
#
# GitHub Actions Scripts
# Copyright (C) 2021-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

# Bash options:
set -e


UNAME=`uname`
if [ "${UNAME}" == "Linux" ] ; then
   DISTRIBUTION=`lsb_release -is`
else
   DISTRIBUTION="Unknown"
fi


# ###### Linux ##############################################################
if [ "${UNAME}" == "Linux" ] ; then

   # ====== Ubuntu/Debian ===================================================
   if [ "${DISTRIBUTION}" == "Ubuntu" -o "${DISTRIBUTION}" == "Debian" ] ; then
      sudo apt update -qq
      sudo env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt dist-upgrade -qy
      sudo env LANG=C.UTF-8 DEBIAN_FRONTEND=noninteractive apt install -qy  -o Dpkg::Options::=--force-confold -o Dpkg::Options::=--force-confdef --no-install-recommends gcc libtool autoconf automake python3

   # ====== Fedora ==========================================================
   elif [ "${DISTRIBUTION}" == "Fedora" ] ; then
      dnf install -qy python3
      dnf upgrade -qy

   # ====== Unknown =========================================================
   else
      echo >&2 "ERROR: Unknown Linux distribution ${DISTRIBUTION}!"
      exit 1
   fi

# ###### FreeBSD ############################################################
elif [ "${UNAME}" == "FreeBSD" ] ; then

   # Nothing to be done here.
   true

# ###### Unknown ############################################################
else

   echo >&2 "ERROR: Unexpected system ${UNAME}!"
   exit 1

fi
