#!/bin/bash -e
#
# Travis CI Scripts
# Copyright (C) 2018-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


UBUNTU_DEPS="cmake gcc g++ clang make libsctp-dev"
FEDORA_DEPS="cmake gcc gcc-c++ clang make lksctp-tools-devel"

# ###### Linux ##############################################################
if [ "$TRAVIS_OS_NAME" = "linux" ] ; then
   # ====== Ubuntu Linux ====================================================
   if [ "$VARIANT" = "ubuntu" -o "$VARIANT" = "debian" ] ; then
      . /etc/lsb-release
      echo "Distribution is $DISTRIB_CODENAME"

      sudo docker exec -t ubuntu-test bash -c "apt-get update"
      # NOTE: locales is needed, to get UTF-8 support right!
      sudo docker exec -t ubuntu-test bash -c "apt-get install -y locales eatmydata"
      sudo docker exec -t ubuntu-test bash -c "eatmydata apt-get install -y ${UBUNTU_DEPS}"
      sudo docker exec -t ubuntu-test bash -c "locale-gen en_US.UTF-8"
      sudo docker exec -t ubuntu-test bash -c "update-locale LANG=en_US.UTF-8 LANGUAGE=en_US.UTF-8 LC_ALL=en_US.UTF-8"
      if [ "$TOOL" = "pbuilder" ] ; then
         sudo docker exec -t ubuntu-test bash -c "eatmydata apt-get install -y devscripts debhelper pbuilder"
         sudo docker exec -t ubuntu-test bash -c "cat >/etc/pbuilderrc <<EOF
DISTRIBUTION=$DISTRIB_CODENAME
COMPONENTS=\"main universe\"
MIRRORSITE=http://us.archive.ubuntu.com/ubuntu/
APTCACHEHARDLINK=no
EOF
"
         sudo docker exec -t ubuntu-test bash -c "cat /etc/pbuilderrc"
         sudo docker exec -t ubuntu-test bash -c "pbuilder create --debootstrapopts --variant=buildd"

         sudo docker exec -t ubuntu-test bash -c "pbuilder login --save-after-login <<EOF
apt install -y software-properties-common
apt-add-repository -sy ppa:dreibh/ppa
apt-get update
EOF
"
      fi

   # ======Fedora Core Linux ================================================
   elif [ "$VARIANT" = "fedora" ] ; then
      sudo docker exec -t ubuntu-test bash -c "dnf install -y ${FEDORA_DEPS}"
      if [ "$TOOL" = "mock" ] ; then
         sudo docker exec -t ubuntu-test bash -c "dnf install -y findutils rpmdevtools fedora-release mock"
      fi

   # ======Fedora Core Linux ================================================
   else
      echo >&2 "ERROR: Invalid setting of VARIANT=$VARIANT"
      exit 1
   fi

# ###### Other ##############################################################
elif [ "$TRAVIS_OS_NAME" = "osx" ] ; then
   echo "TBD"

# ###### Error ##############################################################
else
   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
   exit 1
fi
