.\" TSCTP
.\" Copyright (c) 2005 - 2011 Michael Tuexen, tuexen@fh-muenster.de
.\" Copyright (C) 2009 - 2025 Thomas Dreibholz, thomas.dreibholz@gmail.com
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" ###### Setup ############################################################
.Dd September 16, 2025
.Dt tsctp 1
.Os tsctp
.\" ###### Name #############################################################
.Sh NAME
.Nm tsctp
.Nd SCTP Test Tool
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm tsctp
.Op Fl a Ar indication
.Op Fl A Ar type
.Op Fl D
.Op Fl f Ar fragmentation_point
.Op Fl l Ar buffersize
.Op Fl L Ar local_address
.Op Fl n Ar number_of_messages
.Op Fl p Ar port
.Op Fl R Ar rcvbufsize
.Op Fl S Ar sndbufsize
.Op Fl t Ar timetolive
.Op Fl T Ar runtime
.Op Fl u
.Op Fl U Ar udp_port
.Op Fl v
.Op Fl V
.Op Fl 4
.Op Fl 6
.Op remote_address
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm tsctp
is an SCTP test tool. It can be used to make basic tests with the SCTP
protocol. For the tool to work, the kernel needs to support SCTP, i.e.
sockets with protocol IPPROTO_SCTP.
.Bl -tag -width indent
.It Linux: echo "sctp" >/etc/modules-load.d/sctp.conf
Then, reboot to load the module.
Note: Ensure that the SCTP module is not blacklisted
(e.g. /etc/modprobe.d/sctp-blacklist.conf in Fedora Linux)!
.It FreeBSD: echo 'sctp_load="YES"' >>/boot/loader.conf
Then, reboot to load the module.
.El
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following arguments may be provided:
.Bl -tag -width indent
.It Fl a Ar indication
Set adaptation layer indication.
.It Fl A Ar type
Set chunk type to authenticate .
.It Fl D
Turns Nagle off.
.It Fl f Ar fragmentation_point
Set fragmentation point.
.It Fl l Ar buffersize
Set size of send/receive buffer. For sending messages, this means the message size!
.It Fl L Ar local_address
Set local address.
.It Fl n Ar number_of_messages
Set number of messages to be sent (0 means infinite)/received.
.It Fl p Ar port
Set port number.
.It Fl R Ar rcvbufsize
Set socket recv buffer.
.It Fl S Ar sndbufsize
Set socket send buffer.
.It Fl t Ar timetolive
Set time to live for messages.
.It Fl T Ar runtime
Set time to send messages.
.It Fl u
Set use of unordered messages.
.It Fl U Ar udp_port
Use UDP encapsulation with given port.
.It Fl v
Enable verbose output.
.It Fl V
Enable very verbose output.
.It Fl 4
Use IPv4 only.
.It Fl 6
Use IPv6 only.
.It remote_address
If a remote address is given, the client mode is used. Then, tsctp connects
the socket to the given remote address. Otherwise, without given remote address,
the server mode is used. Then, tsctp listens for incoming connections.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It tsctp -L :: -L 0.0.0.0 -p 1234
Server mode: bind to all IPv4 and IPv6 addresses, listen on port 1234.
.It tsctp -L :: -L 0.0.0.0 -p 1234 -n 10 -l 1000 127.0.0.1
Client mode:
bind to all IPv4 and IPv6 addresses,
connect to localhost (127.0.0.1) on port 1234,
send 10 messages of 1000 bytes each.
.It tsctp -L :: -L 0.0.0.0 -p 1234 -n 0 -T 10 -l 4096 127.0.0.1
Client mode:
bind to all IPv4 and IPv6 addresses,
connect to localhost (127.0.0.1) on port 1234,
send unlimited number of messages of 4096 bytes each,
stop after 10 s.
.El
.\" ###### Authors ##########################################################
.Sh AUTHORS
Michael Tüxen, Robin Seggelmann, Irene Rüngeler, Thomas Dreibholz
.br
https://www.nntb.no/~dreibh/tsctp
