name: Build with CMake

on:
  push:
    branches:
      - master
      - dreibh/github-actions

jobs:
  build:

    # https://github.com/marketplace/actions/run-on-architecture
    strategy:
      matrix:
        platform:
          - ubuntu-20.04
          - ubuntu-18.04

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: |
        sudo ci/get-dependencies ubuntu --install

    - name: Build
      shell: bash
      run: |
        ./autogen.sh
