name: CI Tests

on:
  push:
    branches:
      - master
      - dreibh/github-actions

jobs:
  build_job:

    # ###### Build matrix ###################################################
    strategy:
      matrix:
        include:

          # ====== Debian Linux =============================================
          - label: "Debian 12 (Bookworm) with GCC on x86_64"
            arch: amd64
            distro: bookworm
            cc: gcc
            cxx: g++

          # ====== Fedora Linux =============================================
          - label: "Fedora 35 with Clang on x86_64"
            arch: amd64
            distro: fedora35
            cc: clang
            cxx: clang++
          - label: "Fedora 34 with Clang on x86_64"
            arch: amd64
            distro: fedora34
            cc: clang
            cxx: clang++

          # ====== Ubuntu Linux =============================================
          - label: "Ubuntu 22.04 (Jammy Jellyfish) with GCC on x86_64"
            arch: amd64
            distro: ubuntu22.04
            cc: gcc
            cxx: g++
          - label: "Ubuntu 20.04 (Focal Fossa) with GCC on x86_64"
            arch: amd64
            distro: ubuntu20.04
            cc: gcc
            cxx: g++
          - label: "Ubuntu 18.04 (Bionic Beaver) with GCC on x86_64"
            arch: amd64
            distro: ubuntu18.04
            cc: gcc
            cxx: g++


    # ###### Build commands #################################################
    name: Build on ${{ matrix.label }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dreibh/run-on-arch-action@dreibh/tests
        name: Build
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          run: |
            ci/ci-setup
            ci/ci-install
            env CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-build compile
