name: Build with CMake

on:
  push:
    branches:
      - master
      - dreibh/github-actions

jobs:
  build:

    # https://github.com/marketplace/actions/run-on-architecture
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          #- ubuntu-18.04
          #- bullseye

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      #with:
        #path: 'src'
        #submodules: recursive

    - name: Install dependencies
      shell: bash
      run: |
        ci/get-dependencies ubuntu --install
        ./autogen.sh

    - name: Build
      shell: bash
      run: |
        ci/get-dependencies ubuntu --install
        ./autogen.sh
