name: FreeBSD CI Tests

on:
  push:
    branches:
      - master
      - dreibh/github-actions
      - dreibh/github-actions-freebsd

jobs:
  build_job:

    # ###### Build matrix ###################################################
    strategy:
      matrix:
        include:

          # ====== FreeBSD 13.0 =============================================
          - label: "FreeBSD 13.0: Clang/x86_64"
            cc: clang
            cxx: clang++


    # ###### Build commands #################################################
    name: ${{ matrix.label }}
    runs-on: macos-10.15
    env:
      MYTOKEN: ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        run: |
          ci/ci-setup
          ci/ci-install
          env CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-build compile
