# GitHub Actions Scripts
# Copyright (C) 2021-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

name: Linux CI Tests

on:
  push:
    branches:
      - master
      - dreibh/github-actions

jobs:
  build_job:

    # ###### Build matrix ###################################################
    strategy:
      matrix:
        include:

          # ====== Ubuntu Linux =============================================
          #- label: "Ubuntu 22.04 (Jammy Jellyfish) with GCC"
            ##arch: amd64
            #image: ubuntu:22.04
            #cc: gcc
            #cxx: g++
          - label: "Ubuntu 20.04 (Focal Fossa) with GCC"
            arch: amd64
            image: ubuntu:20.04
            cc: gcc
            cxx: g++
          #- label: "Ubuntu 18.04 (Bionic Beaver) with GCC"
            #arch: amd64
            #distro: ubuntu18.04
            #cc: gcc
            #cxx: g++
          #- label: "Ubuntu 16.04 (Xenial Xerus) with GCC"
            #arch: amd64
            #distro: ubuntu16.04
            #cc: gcc
            #cxx: g++
          #- label: "Ubuntu 14.04 (Trusty Tahr) with GCC"
            #arch: amd64
            #distro: ubuntu14.04
            #cc: gcc
            #cxx: g++

          ## ====== Debian Linux =============================================
          #- label: "Debian 12 (Bookworm) with GCC"
            #arch: amd64
            #distro: bookworm
            #cc: gcc
            #cxx: g++
          #- label: "Debian 11 (Bullseye) with GCC"
            #arch: amd64
            #distro: bullseye
            #cc: gcc
            #cxx: g++
          #- label: "Debian 10 (Buster) with GCC"
            #arch: amd64
            #distro: buster
            #cc: gcc
            #cxx: g++

          ## ====== Fedora Linux =============================================
          #- label: "Fedora 35 with Clang"
            #arch: amd64
            #distro: fedora35
            #cc: clang
            #cxx: clang++
          #- label: "Fedora 34 with Clang"
            #arch: amd64
            #distro: fedora34
            #cc: clang
            #cxx: clang++


    # ###### Build commands #################################################
    name: ${{ matrix.label }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
      #options: "--privileged"

    #steps:
      #- uses: actions/checkout@v2
      #- uses: dreibh/run-on-arch-action@dreibh/tests
        #name: Build
        #id: build
        #with:
          #arch: ${{ matrix.arch }}
          #distro: ${{ matrix.distro }}
          #run: |
            #ci/ci-setup compile
            #ci/ci-install compile
            #env CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ci/ci-build compile
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ARCH= ci/ci-setup   compile
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ARCH= ci/ci-install compile
          CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} ARCH= ci/ci-build   compile
