name: Generic CI Tests

on:
  push:
    branches:
      - master
      - dreibh/github-actions
      - dreibh/github-actions-freebsd

jobs:
  # ====== Ubuntu Linux =====================================================
  #ubuntu-packaging:
    #name: Ubuntu Packaging
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Packaging
      #shell: bash
      #run: |
        #sudo ci/ci-setup compile package
        #sudo ci/ci-install compile package
        #env CC=gcc CXX=g++ OS=ubuntu DIST=jammy ARCH= sudo ci/ci-setup   package
        #env CC=gcc CXX=g++ OS=ubuntu DIST=jammy ARCH= sudo ci/ci-install package
        #env CC=gcc CXX=g++ OS=ubuntu DIST=jammy ARCH= sudo ci/ci-build   package

  # ====== Debian Linux =====================================================
  debian-packaging:
    name: Debian Packaging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Packaging
      shell: bash
      run: |
        env CC=gcc CXX=g++ OS=debian DIST=unstable ARCH= sudo ci/ci-setup   package
        env CC=gcc CXX=g++ OS=debian DIST=unstable ARCH= sudo ci/ci-install package
        env CC=gcc CXX=g++ OS=debian DIST=unstable ARCH= sudo ci/ci-build   package

   # ====== Fedora Linux ====================================================
  #fedora-packaging:
    #name: Fedora Packaging
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Packaging
      #shell: bash
      #run: |
        #sudo ci/ci-setup compile package
        #sudo ci/ci-install compile package
        #env CC=clang CXX=clang++ ci/ci-build package
